// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: phones.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createPhone = `-- name: CreatePhone :exec
INSERT INTO phones
(id, description, phone, owner_id)
VALUES
($1,$2,$3,$4)
`

type CreatePhoneParams struct {
	ID          uuid.UUID `json:"id"`
	Description string    `json:"description"`
	Phone       string    `json:"phone"`
	OwnerID     uuid.UUID `json:"owner_id"`
}

// Active: 1691937846246@@127.0.0.1@9500@sistema-escolar
func (q *Queries) CreatePhone(ctx context.Context, arg CreatePhoneParams) error {
	_, err := q.db.ExecContext(ctx, createPhone,
		arg.ID,
		arg.Description,
		arg.Phone,
		arg.OwnerID,
	)
	return err
}
