// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: registration.sql

package postgres

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRegistration = `-- name: CreateRegistration :exec

INSERT INTO registrations 
    (id, code, class_room_id, shift, student_id, 
     service_id, monthly_fee, installments_quantity,
     enrollment_fee, due_date, month_duration, status,
     enrollment_date, school_year_id, created_at, updated_at)
    VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)
`

type CreateRegistrationParams struct {
	ID                   uuid.UUID      `json:"id"`
	Code                 string         `json:"code"`
	ClassRoomID          uuid.NullUUID  `json:"class_room_id"`
	Shift                sql.NullString `json:"shift"`
	StudentID            uuid.UUID      `json:"student_id"`
	ServiceID            uuid.UUID      `json:"service_id"`
	MonthlyFee           string         `json:"monthly_fee"`
	InstallmentsQuantity int32          `json:"installments_quantity"`
	EnrollmentFee        sql.NullString `json:"enrollment_fee"`
	DueDate              sql.NullTime   `json:"due_date"`
	MonthDuration        sql.NullInt32  `json:"month_duration"`
	Status               string         `json:"status"`
	EnrollmentDate       sql.NullTime   `json:"enrollment_date"`
	SchoolYearID         uuid.NullUUID  `json:"school_year_id"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

// Active: 1691937846246@@127.0.0.1@9500@postgres
func (q *Queries) CreateRegistration(ctx context.Context, arg CreateRegistrationParams) error {
	_, err := q.db.ExecContext(ctx, createRegistration,
		arg.ID,
		arg.Code,
		arg.ClassRoomID,
		arg.Shift,
		arg.StudentID,
		arg.ServiceID,
		arg.MonthlyFee,
		arg.InstallmentsQuantity,
		arg.EnrollmentFee,
		arg.DueDate,
		arg.MonthDuration,
		arg.Status,
		arg.EnrollmentDate,
		arg.SchoolYearID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
